#1 issue fixed | progress tint matched
VishnuSanal/DialogMusicPlayer pull request #2
Opened 2021-10-02 14:36 UTC by AP-Atul

Timer issue fixed.

## suggestions
1. We can add a service that can show a notification cause right now if we leave the dialog window the music will keep playing and if we close the file explorer, we can't go back to the dialog.
2. If you want i can do that

2021-10-03 06:55 UTC, VishnuSanal commented
Hello @AP-Atul!

> Timer issue fixed.

What was the issue with timer?!

> ## suggestions
> 1. We can add a service that can show a notification cause right now if we leave the dialog window the music will keep playing and if we close the file explorer, we can't go back to the dialog.
> 2. If you want i can do that

As this is a open source project, contributions are always welcome. Please create an issue & go ahead!

PS: I'll add the license etc meanwhile, so that it can be an open-source project! ;D

2021-10-03 07:47 UTC, VishnuSanal requested changes
@AP-Atul Awesome work!

Please address these comments too.

2021-10-03 07:47 UTC, VishnuSanal commented on app/src/main/java/phone/vishnu/dialogmusicplayer/MainActivity.java
> +            setRequestedOrientation(ActivityInfo.SCREEN_ORIENTATION_UNSPECIFIED);
Why? This would cause the same music to play multiple times. This was a hack to avoid that!

2021-10-03 07:47 UTC, VishnuSanal commented on app/src/main/java/phone/vishnu/dialogmusicplayer/MainActivity.java
> +        mediaPlayer.stop();
Why not `release()`?

2021-10-03 07:47 UTC, VishnuSanal commented on app/src/main/res/layout/activity_main.xml
> +            android:progressTint="@android:color/holo_red_light"
LGTM :D

2021-10-03 07:51 UTC, VishnuSanal commented
BTW: Moving logically different changes to multiple commits is recommended (:

2021-11-25 09:36 UTC, VishnuSanal commented
@AP-Atul Is this still active? Thanks!

2021-11-25 09:41 UTC, AP-Atul commented
No. Giving up on it

2021-11-25 09:41 UTC, closed without merging

2021-11-25 09:42 UTC, VishnuSanal commented
@AP-Atul Okay, anyways, thanks for your suggestions & PR! :)